### PR TITLE
Table Styles Refactor

### PR DESCRIPTION
**Pull request by devowhippit**
Modularized table styles into mixins and added `elements/tables/_tables.config.scss` to the pattern's directory. Let me know what you think of that approach instead of having a `config/_tables.scss` file.

This will help me fix an issue on the Screening Docs as well as make the table styling more importable into custom selector definitions. The reorganization may just be a nice thing to use future approaches of organizing pattern dependencies.

### CODE REVIEW

**Comment by KISS** [comment]
Are you not able to use the mixins without separating the table styles into a config directory/file extension? 

For now, I vote we keep the current structure of using `src/config` to avoid extra abstractions. If we decide to use the `.config.scss` extension, it should be implemented across the codebase at once so it's all uniform and easy to replicate.

**Comment by kimpenguin** [comment]
I like it merely due to the ease of updating a mixin, but I think the original method of keeping configurations in `config/` makes sense if you need to import the table mixins into other elements. Just thinking of the paths now add more complexity than necessary.

**Comment by devowhippit** [comment]
@KISS Are you not able to use the mixins without separating the table styles into a config directory/file extension?

The mixins can't be extended, for example in the Screening API docs;

.o-content {
  table {
    @include table();
  }
}

This actually renders as

**Comment by KISS** [comment]
Ah ok, I didn't set up the mixins properly when I updated the tables then. My bad.

**Comment by devowhippit** [comment]
@KISS not your fault. Not many of the patterns were set up this way so there was no precedent before.

**Comment by devowhippit** [comment]
I just realized I didn't set it up right either!

**Comment by devowhippit** [comment]
@kimpenguin and @KISS updated the PR with the recommendations.

**Comment by devowhippit** [comment]
Added some other small fixes to the input element.

**Pull request merged**
